### ISSUE TITLE
Implement spec 1.0 changes

### ISSUE THREAD

**Issue by brianjmiller** [RusticiSoftware/TinCanJS#32]
Land changes that occur for spec 1.0.

Requirements:
- [x] Bump version list (#33)
- [x] Context Activities as arrays (#33)
- [x] deprecated 'voided' (#33)
- [x] Add Statement 'version' property (#33)
- [x] Query API (authoritative removal, mode expansion) (#33)
- [x] Fetch voided statements (#33)
- [ ] Anonymous Groups
- [x] Document merge/partial updates (State, Activity Profile, Agent Profile)
- [x] Statement attachments
- [ ] Statement signing
- [ ] Fetch of URL related items
- [x] About request + auto detection of LRS version
- [x] Activity Definition "moreInfo" property
